### ISSUE TITLE
Inconsistent keyword classification

### ISSUE THREAD

**Issue by EleanorNB** [maxxnino/tree-sitter-zig#21]
https://github.com/folke/tokyonight.nvim renders keywords in italics by default, however it italicises this grammar's keywords inconsistently. I've identified that it italicises `defer`, `suspend`, `nosuspend`, `await`, `async`, and `pub`, but does not italicise `fn`, `const`, `var`, `try`, `catch`, `orelse`, `and`, or `or`. I haven't exhaustively tested all keywords.

Is this issue on our end? If so, is it just an error, or is it intentional? I can't identify any pattern.

**Comment by maxxnino** [comment]
The grammar is perfectly fine. The problem is when we use it. And since I don't have good experience with zig keyword. what should they call. I only use my best guess

https://github.com/nvim-treesitter/nvim-treesitter/blob/0e6d4b4172f30c4aa44a9adc9ea5719723a1fac3/queries/zig/highlights.scm#L93-L100

https://github.com/nvim-treesitter/nvim-treesitter/blob/0e6d4b4172f30c4aa44a9adc9ea5719723a1fac3/queries/zig/highlights.scm#L145-L161

**Comment by EleanorNB** [comment]
Ah, I see the problem. The theme doesn't detect keyword subtypes. Looking at the grammars for Rust[^1] and Go[^2], they don't subtype their keywords, and just put them all in one big clump; think we should do the same? If so I can make the edit.

[^1]: https://github.com/tree-sitter/tree-sitter-rust/blob/master/queries/highlights.scm
[^2]: https://github.com/tree-sitter/tree-sitter-go/blob/master/queries/highlights.scm

**Comment by EleanorNB** [comment]
Actually no, screw this theme. You're doing the right thing by splitting them and it should be the theme that handles it better. Remind me in the morning, I'll harass them about it.
